/*
*****************************
****** Rules Variables ******
*****************************
*/
life_ruleInfo = 
[
	[1,"GENERALITES",0,"<t size='0.8'><t color='#FF0000'>Ce menu défini les règles du serveur ainsi que des informations importantes.</t><br/><br/>• Les règles sont susceptibles de changer, si tel est le cas, à votre connexion, une nouvelle acceptation des règles sera demandée<br/>• Le système d'acceptation obligatoire des règles rends les excuses concernant la non-connaissance des règles irrecevables.<br/>• Les sanctions indiquées dans ce menu sont données à titre indicatif, et représentent une base qui sera adaptée selon la situation.<br/>• Toute forme de hack, utilisation de bug, cheat ou autre moyen de transgresser les sécuritées mises en place sera sanctionné d'un ban permanent<br/>• Toute insulte ou manque de respect sera sanctionné d'une ban dont la durée sera determinée par un administrateur.</t>"],
	[2,"TALENTS",0,"<t size='0.8'>Un système de talent est disponible ! Vous le trouverez dans votre menu d'inventaire (Y). Toutes les informations nécessaires s'y trouvent.</t>"],
	[3,"TOUCHES",0,"Voici les touches principales d'interactions en jeu:<br/><br/><t size='0.8'>• Y: Ouvrir l'interface joueur<br/>• U: Verrouiller ou déverouiller portes/véhicules<br/>• F: Sirène (si gendarme)<br/>• T: Coffre du véhicule/de votre maison<br/>• Shift Gauche + R: Menotter (si Gendarme)<br/>• Shift Gauche + P: Baisser/Monter le Son<br/>• Shift Gauche + G: Assomer (Civils seulement, à utiliser pour voler)<br/>• Windows Gauche: Touche d'intéraction principale, utilisée pour les véhicules (réparer, etc.), pour ramasser des items au sol (argent, objets, etc.), et pour les Gendarmes (intéractions joueur). Peut être remplacé par une touche comme H en assignant une touche dans Echap->Configurer->Commandes->Touches perso.->Util. Action 10<br/>• Shift + L: Activer les gyrophares (si Gendarme)<br/>• Shift + H: Ranger votre arme<br/>• Ctrl + H: Sortir votre arme<br/>• Ctrl + E: Se rendre (mettre les mains sur la tête)</t>"],
	[4,"REGLES GENERALES",0,"Ici sont regroupées toutes les règles générales."],
	[5,"Exploits/Glitchs",1,"<t size='0.8'>Les points suivants seront considérés comme exploit/glitch, vous ne serez pas kick, mais ban.<br/><br/>• Sortir de la prison par tout autre moyen que de payer la caution ou de sortir par hélicoptère.<br/>• Vous suicider pour éviter une action. Par exemple se faire tazé, arrêté, mis en prison, etc. Si les logs prouvent que vous vous êtes fait arrêté, et que vous êtes mort, vous serez banni. Ne vous suicidez pas après avoir payé la caution pour revenir plus rapidement chez vous. Faites le trajet de manière RP.<br/>• Duplication d'item et/ou d'argent. Si quelqu'un vous envoie un montant exorbitant d'argent sur votre compte en début de jeu, merci de report ce joueur à un admin IMMEDIATEMENT et de transférer cet argent à un admin. Faites le dès que possible, ou un admin pourrait vous bannir si il vous voit avec une tel somme sur vous.<br/>• Utiliser des items provenant d'un hack. Si un hacker vient à faire spawn des items que vous ne pouvez obtenir normalement en jeu, vous pourrez vous faire bannir pour les avoir utilisés. Merci de report le hacker, ainsi que ces dits-items à un admin et de vous éloigner de ceux-ci.<br/>• Abuser de bugs et/ou de mécaniques de jeu pour gagner.</t>"],
	[6,"Actions menant à un ban",1,"<t size='0.8'>Considérez ceci comme votre premier et votre dernier avertissement.<br/><br/>• Hacking<br/>• Cheating<br/>• Exploit/Use bug (voir Exploits/Glitchs)<br/>• Vous faire kick 3 fois ou plus.</t>"],
	[7,"Interactions avec la Gendarmerie",1,"<t size='0.8'>Les points suivants peuvent être passible d'une suppression de votre personnage sur le serveur ou d'un ban, variable selon la décision de l'admin.<br/><br/>• Un civil peut être arrêté pour avoir ouvert le sac d'un gendarme ou le coffre de son véhicule. Répéter cet action plusieurs fois peut entraîner un kick/ban.<br/>• Un civil peut être arrêté pour avoir suivi un gendarme trop longtemps dans le but de donner sa position aux autres joueurs.<br/>• Le meurtre d'un gendarme par un civil ou rebelle armé en ville ou dans tout autre endroit sans raison RP sera considéré comme du freekill. Voir la section Freekill.<br/>• Suivre et/ou harcelé un/des gendarmes peut être considéré comme du troll/spam, et peut résulter en un kick.<br/>• Empêcher sciemment les gendarmes d'exercer leur devoir peut résulter par votre arrestation. Le faire de manière abusive et répétée peut résulter en un kick.</t>"],
	[8,"Bâteaux",1,"<t size='0.8'>Les points suivants peuvent être passible d'une suppression de votre personnage sur le serveur ou d'un ban, variable selon la décision de l'admin.<br/><br/>• Pousser les bâteaux de manière répétée sans permission.<br/>• Pousser un bâteau dans l'intention de blesser/de tuer quelqu'un n'est pas RP.<br/>• Percuter des plongeurs/nageurs. Cette action est considéré comme du car-kill.</t>"],
	[9,"Aviation",1,"<t size='0.8'>Les points suivants peuvent être passible d'une suppression de votre personnage sur le serveur ou d'un ban, variable selon la décision de l'admin.<br/><br/>• Faire exprès d'écraser son hélicoptère dans quelque chose. Que ce soit d'autres hélicoptères, véhicules, ou bâtiments.<br/>• Voler constamment en dessous de 150 mètres au dessus d'une ville. Une fois c'est illégal, mais si cela se reproduit vous risquez de vous crasher en ville, ce qui est interdit par le point précédent.<br/>• Voler un hélicoptère sans que son pilote ai eu le temps de verrouiller son véhicule. Si l'hélicoptère se pose et que son pilote part en courant sans le verrouiller, très bien. Si il déverouille son hélicoptère pour descendre et que vous montez en pilote sans lui laisser le temps de le verouiller, non.</t>"],
	[10,"Véhicules",1,"<t size='0.8'>Les points suivants peuvent être passible d'une suppression de votre personnage sur le serveur ou d'un ban, variable selon la décision de l'admin.<br/><br/>• Faire exprès d'écraser quelqu'un (Carkill). Il y a des accidents, et il y a sortir de la route pour écraser quelqu'un.<br/>• Se jeter sous les roues d'un véhicules pour se faire blesser/tuer.<br/>• Foncer dans les autres véhicules pour les faire exploser. Vous pouvez rammener les autres véhicules pour les neutraliser, mais faites attention à ne pas l'exploser, sinon cela se retournera contre vous.<br/>• Constamment essayer d'enter dans des véhicules qui ne vous appartiennent pour troller son propriétaire.<br/>• Voler un véhicule juste pour le planter ou encore le détruire.<br/>• Acheter/louer des véhicules dans le but de faire une des actions listées ci-dessus.<br/>• La seule raison pour ouvrir le feu sur un véhicule est pour le neutraliser et/ou pour faire un tir de sommation dans un contexte RP. Vous ne pouvez pas déliberrement faire feu sur les véhicules sans raisons.</t>"],
	[11,"Règles de communication",1,"<t size='0.8'>Les points suivants peuvent être passible d'une suppression de votre personnage sur le serveur ou d'un ban, variable selon la décision de l'admin.<br/><br/>• Le Side-Chat n'est pas un salon de thé. Toute communication orale sur le side-chat résultera d'un kick.<br/>• Flooder n'importe quel canal de communication résultera d'un kick/ban.<br/>• Les channels TeamSpeak sont séparées en plusieurs catégories pour de bonnes raisons. Ne vous mélangez pas pour éviter les débordements non-RP.<br/>• Un civil se trouvant dans le channel TeamSpeak de la gendarmerie pour les espionner/collecter des informations sur leurs agissements se verra kick du TS dans un premier lieu, puis ensuite ban du TS et du serveur.</t>"],
	[12,"Freekill",1,"<t size='0.8'>Les points suivants peuvent être passible d'une suppression de votre personnage sur le serveur ou d'un ban, variable selon la décision de l'admin.<br/><br/>• Tuer quelqu'un sans aucune raison Roleplay.<br/>• Faire partie des rebelles ne veut pas dire tuer les gens à vue, même les gendarmes.<br/>• Les gendarmes et civils/rebelles sont en droit de se tirer dessus si le conflit tourne autour d'un crime, roleplay parlant.<br/>• Si vous vous balladez au milieu d'une fusillade et que vous êtes tué, ce n'est pas du Freekill.<br/>• Tuer quelqu'un dans le but de vous protéger ou de protéger les autres n'est pas du Freekill. Cependant, réfléchissez avant de tirer.<br/>• Tuer un joueur sans lui laisser le temps de se soumettre aux sommations est considéré comme du Freekill.<br/><br/>Les conflits relatant du freekill seront jugés par les admins au cas-par-cas.</t>"],
	[13,"Nouvelle vie",1,"<t size='0.8'>La règle de la nouvelle vie s'applique à tout le monde, même aux gendarmes.<br/><br/>Les points suivants peuvent être passible d'une suppression de votre personnage sur le serveur ou d'un ban, variable selon la décision de l'admin.<br/><br/>• Si vous êtes morts lors d'une action RP/fusillade, vous devrez attendre 15 minutes avant de revenir sur les lieux. (excepté gendarmerie, délai de 5mn en braquage de banque)<br/>• Si vous mourrez, vos crimes précédents seront oubliés. Cependant, vous ne pouvez pas chercher vengeance non plus. C'est une NOUVELLE VIE.<br/>• Si vous vous êtes fait freekill, ce n'est PAS une nouvelle vie.<br/>• Si vous respawnez manuellement (lobby, déco/reco, etc.), ce n'est pas une nouvelle vie.<br/>• Si vous vous suicidez exprès pour éviter une action RP, ce n'est pas une nouvelle vie.</t>"],
	[14,"Règle ultime",1,"<t color='#FF0000'>Arrête d'être con !</t><br/><br/><t size='0.8'>Si un admin vous dit que vous enfreignez les règles, alors vous faites probablement de la merde.<br/>Troller les autres, manquer de Roleplay,etc. : et la liste est longue.<br/>Arrêtez simplement de faire n'importe quoi, ok ?<br/>Cette règle peut être invoquée par un admin selon sa décision.</t>"],
	[15,"ROLE PLAY",0,"<t size='0.8'>Le RolePlay (RP) est une notion assez facile à  comprendre, il s'agit de jouer un rôle, incarner un personnage. Dans Altis Life, vous pouvez très bien incarner un civil schizophrène, un rebelle peureux (et oui !) ou bien un gendarme n'éprouvant aucun remord à vous verbaliser. C'est à vous de forger l'histoire de votre personnage.</t>"],
	[16,"Mort",1,"<t size='0.8'>Etant donné que mourrir est fréquent, nous n'imposons pas la création d'un nouveau personnage à chaque mort. La mort correspond à un séjour en soins intensifs à l'hôpital. En revanche, vous vous devez de respécter les règles suivantes : <br/><br/>• Interdiction de retourner sur les lieux de la mort pendant 15 minutes<br/>• Interdiction de donner des informations concernant sa mort susceptible d'aider des joueurs encore vivants<br/>• Vous avez oublié toute information concernant votre meurtrier, vous ne pouvez pas vous venger. C'est une nouvelle vie.</t>"],
	[17,"Mort RP",1,"<t size='0.8'>Si vous souhaitez commencer une nouvelle vie, merci de poster un message sur le forum. Toutes les données concernant votre personnage seront supprimées et vous repartirez à zéro.</t>"],
	[18,"Reboot Serveur",1,"<t size='0.8'>Lors d'un reboot serveur, vous ne commencez pas une nouvelle vie, à votre réapparition, vous reprennez votre vie comme après une nuit de sommeil.</t>"],
	[19,"SAFE ZONES",0,"<t size='0.8'>Si vous explosez de manière intentionnelle un véhicules, volez quelqu'un, ou tuez quelqu'un dans ou autour des safe-zones, vous êtes passible d'un ban. Voici la liste des safe zones : <br/>• Tous les points de spawn de véhicules (concesionnaires, garages)<br/>• La globalité de Kavala<br/>• Magasins en ville<br/>• Concessionnaires<br/>• Gendarmeries<br/>• Campement guérillero<br/>• R.S Dépannage<br/>• Armureries<br/>• Magasin Donateur</t>"],
	[20,"CIVILS",0,"<t size='0.8'>Rubriques concernant les civils, sont civils tout ceux n'étant ni guérillero, ni gendarme, ni médecin en service.</t>"],
	[21,"Débuter",1,"<t size='0.8'>Lors de votre première connexion, vous êtes un civil. Vous ne possédez que vos vêtements, une carte, une montre, une boussole et 3000 €. Votre objectif est de gagner de l'argent par le biais des métiers disponibles sur la carte.</t>"],
	[22,"Interactions",1,"<t size='0.8'>L'interpretation de votre personnage signifie aussi être cohérent avec la situation. En effet, si un rebelle vous braque, et que vous n'êtes pas armé, ne jouez pas les durs. Il sera considéré non-rp de ne pas se soumettre dans un situation où, dans la vie réelle, vous n'auriez pas le choix. Votre vie passe avant tout.</t>"],
	[23,"Armes et Utilisations",1,"<t size='0.8'>Un civil peut s'armer légalement en possédant un permis de port d'arme, puis en achetant une arme dans une armurerie. Cette arme devra être rangée dans le holster ou dans le dos (Shift + H) en ville et ne sera ressortie (Ctrl + H) que 100m après la ville. Cette arme ne constitue pas une autorisation de faire du tir au pigeon ! Elle ne devra être utilisée que pour défendre votre vie et devra se faire dans le cadre d'une scène RP</t>"],
	[24,"GENDARMERIE",0,"<t size='0.8'>Toutes règles concernant les Gendarmes sont regroupées ici.</t>"],
	[25,"Gestion de crise",1,"<t size='0.8'>Une gestion de crise (prise d'otage, etc.) doit être gérée par un Lieutenant. Si aucun Lieutenant n'est disponible, la personne la plus haut gradée doit gérer la situation.</t>"],
	[26,"Résèrve d'Etat",1,"<t size='0.8'>Règles concernant la Résèrve d'Etat.<br/>• Il est illégal pour les civils d'entrer dans la Résèrve d'Etat, sauf autorisation par les forces de l'ordre. Si un civil entre dans la zone, il sera escorté vers l'extérieur, puis arrêté si il persiste.<br/>• Les hélicoptères survolant la Résèrve d'Etat seront sommés de partir de la zone, puis neutralisés si ils persistent/refusent.<br/>• Lors d'un braquage de la Résèrve d'Etat, il est recommandé que toutes les forces de Gendarmerie en service se rendent sur les lieux pour empêcher le braquage.<br/>• Tout gendarme proche de la Résèrve d'Etat lors d'un braquage doit se rendre sur place.<br/>• La force létale peut être utilisée sur les braqueurs si aucune alternative n'est disponible. Taser et arrêter les suspects reste la priorité numéro 1.<br/>• Les forces de l'ordre ne peuvent pas tirer à l'aveuglette dans le bâtiment de la Résèrve d'Etat.<br/>• Les forces de l'ordre doivent évacuer les civils présent à la Résèrve d'Etat durant un braquage, pour la sécurité de tous.<br/>• Tout civil empêchant les forces de l'ordre d'entrer dans le bâtiment de la Résèrve d'Etat durant un braquage pourra être considéré comme complice, et donc arrêté.<br/>• Les officiers supérieurs peuvent engager une entreprise ou un groupe pour sécuriser/monter la garde à la Résèrve d'Etat. Voir la section 'Contrat' pour + d'informations.</t>"],
	[27,"Aviation",1,"<t size='0.8'>L'espace aérien d'Altis est régi par des règles très stricts pour éviter la surchage du trafic aérien. En voici les principaux points.<br/>• Aucun hélicoptère n'est autorisé à se poser en ville sans autorisation d'un officier de Gendarmerie.<br/><br/>• Interdiction pour un hélicoptère de se poser sur la route.<br/>• La gendarmerie peut verrouiller l'espace aérien d'une ville, seulement pendant une durée limitée.<br/>• Les hélicoptères ne doivent pas voler en dessous de 150 mètres sans autorisation.<br/>• Aucun hélicoptère ne devra voler en auto-stationnaire au dessus d'une ville. Seuls les pilotes de Gendarmerie pourront le faire dans le cadre d'une opération de Gendarmerie/d'ordre d'un supérieur.</t>"],
	[28,"Zones illégales",1,"<t size='0.8'>• Les planques des gangs ne sont pas considérés illégaux. Un gendarme pourra y entrer sans effectuer un raid, mais ne pourra pas arrêter/menotté quelqu'un sans motif.<br/>• Interdiction d'entrer dans une zone illégal sauf si un raid est en cours. Voir la section 'Raid/Camping'.<br/>• Si vous poursuivez quelqu'un dans une zone illégal, appelez des renforts.<br/>• Un gendarme ne pourra pas camper sur une zone illégal sous aucune circonstance.</t>"],
	[29,"Patrouilles",1,"<t size='0.8'>• La Gendarmerie peut patrouiller sur les routes et dans les villes de l'île à la recherche de véhicules abandonnés et d'activités criminelles.<br/>• Les patrouilles peuvent être effectuées et à l'extérieur des villes ou en dehors, à pied ou en véhicule.<br/>• Les patrouilles n'incluent pas les zones illégales. Voir la section 'Raid/Camping'."],
	[30,"Points de Contrôles",1,"<t size='0.8'>Les gendarmes sont encouragés à placer des points de contrôles à des endroits stratégiques pour aider à combattre les activités illégales et améliorer la sécurité sur la route.<br/><br/>• Un point de contrôle pourra être placé par 3 gendarmes minimum ou plus, avec l'utilisation de 2 véhicules ou plus. Le quad ne peut pas être utilisé.<br/>• Un point de contrôle ne pourra prendre place a moins de 300m d'une zone illégale. Vous ne pourrez donc pas créer un point de contrôle sur une zone illégale.<br/>• Les gendarmes ne peuvent pas établir un point de contrôle sur un carrefour ou un croisement.<br/>• Il est interdit pour un gendarme de marquer un point de contrôle sur la carte.</t>"],
	[31,"Véhicules",1,"<t size='0.8'>• Les véhicules correctement garés sur des places de parking ou à-cheval sur un trottoir (ne gênant pas la circulation) peuvent stationner 30 minutes maximum.<br/>• Les véhicules qui ont l'air abandonnés, cassés, sans conducteur, peuvent être mis en fourrière.<br/>• Les bateaux doivent accostés correctement sur le quai, sans gêner le départ/l'arrivée d'autres bâteaux.<br/>• N'importe quel véhicule gênant la circulation/abandonné qui ne s'est pas déplacé dans un temps significatif peut être mis en fourrière.<br/>• La mise en fourrière est une fonction essentielle d'un gendarme, cela permet de nettoyer les rues et de préserver la qualité de jeu du serveur.<br/>• En cas de doute, fouillez toujours le véhicule et relevez la plaque d'immatriculation (recherche propriétaire) avant de le mettre en fourrière.<br/>• Votre arme ne sera utilisée sur un véhicule seulement pour neutraliser un véhicule en fuite/illégal (crever les pneus, etc.) sans le faire exploser. Privilégier la poursuite si le véhicule tente de s'enfuir en premier temps.</t>"],
	[32,"Vitesses",1,"<t size='0.8'>La gendarmerie doit faire respecter les limites de vitesse sur toutes les routes du territoire de Altis pour la sécurité de ses citoyens.<br/><br/>Villes: Intérieur<br/>• Petites routes: 30Km/h<br/>• Routes principales: 50Km/h<br/><br/>Villes: Extérieur<br/>• Petites routes: 90Km/h<br/>• Routes principales: 120Km/h<br/></t>"],
	[33,"Patrouilles en ville",1,"<t size='0.8'>• Avant de patrouiller, demandez une affectation à l'officier qui s'occupe du dispatch. Vous ne pouvez pas patrouiller seul, et sans en avoir eu la permission par votre supérieur.<br/>• Les gendarmes peuvent patrouiller dans toutes les villes majeures - Roenne, Hasle et Nexoe -, ainsi que dans les petits villages.<br/>• Les gendarmes peuvent s'arrêter en passant devant le concessionnaire pour s'assurer qu'il n'y ai aucune voiture qui nécessite une mise en fourrière.<br/>• Lors de vos patrouilles en ville, ne traînez pas que du côté du centre-ville. Elargissez votre périmètre de patrouille à toute la ville, en passant par les petites routes et la périphérie dans certains cas.<br/>• Il est illégal pour les civils d'entrer dans le commissariat et/ou dans les bâtiments des commissariats sans autorisation. Cependant, il n'est PAS illégal pour un civil de traîner devant l'entrée de ceux-ci, tant qu'il ne cause aucune nuisance.</t>"],
	[34,"Arrestations et amendes",1,"<t size='0.8'>Un civil doit être arrêté si il représente un danger pour lui même/les autres.<br/><br/>• Vous ne pouvez pas arrêter quelqu'un à qui vous avez donné une amande et qui l'a payée.<br/>• Vous devez dire au suspect le motif de l'arrestation avant de procéder à l'arrestation.<br/>• Si un civil est recherché, vous pouvez l'arrêter. Ne le tuez pas, à moins que la situation fasse appel à la section 'Force létale'.<br/><br/>Une amende (verbalisation) est considéré comme un avertissement. S'il viole une loi mais ne représente cependant pas une menace pour lui/les autres, vous pouvez lui infliger une amende.<br/><br/>• Les amendes doivent correspondre avec le tableau des amendes (disponible sur le forum, section Centrale de Gendarmerie).<br/>• Le montant d'une amende doit être basé sur le/les crime(s) commis.<br/>• Un civil refusant de payer une amende pourra se faire arrêter.<br/>• Infliger une amande excessive, comme 100 000€ pour excès de vitesse, etc. est INTERDIT et peut résulter en votre exclusion des services de Gendarmerie.<br/><br/>Une liste de tous les crimes avec leurs sanctions doit être donnée aux gendarmes en formation. Si vous avez un doute, ou si vous n'avez pas connaissance de cette liste, demandez à un supérieur ou reportez vous au tableau des amandes sur TeamSpeak ou sur le forum.</t>"],
	[35,"Armes",1,"<t size='0.8'>Un gendarme ne doit EN AUCUN CAS fournir une arme à un civil, ceci entraînera un ban du serveur et/ou une exclusion de la gendarmerie.<br/><br/>Armes légales (sous résèrve de permis de port d'arme):<br/>• CZ 452<br/>• CZ 550<br/>• Flash-Ball<br/>• CZ 75<br/>• SW 659<br/>• VP 70<br/>• Glock 19<br/><br/>Toutes les autres armes sont illégales.<br/><br/>• Les civils ne sont pas autorisés à avoir leur arme sortie en ville. Ils doivent la ranger soit dans le coffre de leur véhicule, soit dans leur sac à dos.<br/>• Les civils peuvent avoir leur arme en main à l'extérieur d'une ville. Cependant, ils doivent se soumettre à une vérifiacation du permis de port d'arme si ils sont confrontés à un gendarme et doivent baisser leur arme (Deux fois CTRL).</t>"],
	[36,"Force non-létale",1,"<t size='0.8'>Pour le moment, le taser X-26 est la seule arme non-létale.<br/><br/>• Le taser doit être utilisé pour neutraliser les civils non-coopératifs afin de les menotter.<br/>• Ne pas abuser du taser sur un civil, les utilisations non-justifiées mèneront à votre suspension.<br/>• Utilisez votre taser dans la conformité des lois et des règles en vigueur, NE PAS vous défouler sur les autres.</t>"],
	[37,"Raids / Camper une zone",1,"<t size='0.8'>Un raid est défini comme un groupe de gendarmes investissant une zone illégale / zone à haut risque pour arrêter les criminels s'y trouvant.<br/><br/>• Pour pouvoir procéder à un raid, les gendarmes sur place devront être au minium 4, et l'un d'eux doit être Adjudant ou plus haut gradé.<br/>• Tous les civils peuvent être menottés et fouillés lors d'un raid. Si rien d'illégal n'est trouvé sur eux, vous pouvez les laissez partir.<br/>• Si des objets illégaux sont trouvés pendant les fouilles, vous devrez procéder à une arrestation en suivant la procédure habituelle.<br/>• La force létale n'est autorisé comme décrit dans la section 'Force létale'<br/>• Après avoir sécurisé la zone, les gendarmes doivent la quitter.<br/>• Un temps de 30 minutes devra être respecté entre deux raids sur un même endroit.<br/>• Si le raid échoue (tous les gendarmes sont décédés), le temps de 30 minutes sera quand même appliqué.<br/>• Des gendarmes supplémentaires peuvent être appelés en renfort, tant qu'ils ne sont pas morts sur zone durant l'action (Voir 'Règle de la nouvelle vie').<br/><br/>Camper est défini comme étant un gendarme restant sur zone pendant une longue période de temps.<br/><br/>• Être à un point de contrôle n'est pas défini comme camper. Voir la partie 'Points de contrôle' pour les procédures et les règles à suivre.<br/>• Voir les parties 'Braquage de banque' pour plus d'informations sur le fait de camper dans les villes principales.<br/>• Camper une zone illégale, c'est rester plus longtemps que nécessaire après un raid, ou si ils ne font pas un raid, sont présents pour surveiller et agir en conséquence sur les civils entrant dans la zone.</t>"],
	[38,"Echelle de commandement",1,"<t size='0.8'>Le gendarme le plus haut gradé connecté est en charge des forces de l'ordre en présence sur l'île. Le gendarme le plus haut gradé devra suivre les règles, procédures et engagements propres à son grade et au réglement général, et devra se reporter aux admins lorsqu'une décision importante devra être prise.<br/><br/>Chaîne de Commandement de la Gendarmerie:<br/>• Capitaine<br/>• Lieutenant<br/>• Sous-Lieutenant<br/>• Adjudant-Chef<br/>• Adjudant<br/>• Sergent<br/>• Brigadier-Chef<br/>• Brigadier<br/>• Gendarme<br/>• Gendarme Adjoint Volontaire (GAV)<br/><br/>Tous les gendarmes dis 'Public-Slot' sont au grade le plus bas, et n'ont rien à redire à propos des opérations de Gendarmerie.</t>"],
	[39,"Force létale",1,"<t size='0.8'>• L'utilisation de la forcé létale n'est permise que dans le cas ou vous devez protéger votre vie, la vie d'un autre gendarme ou la vie d'un civil, et seulement si la force non-létale ne serait pas efficace.<br/>• Tirer avec une arme sans être en service ou pendant un exercice n'est pas autorisé. Cela peut mener à un kick puis une suspension de la Gendarmerie.<br/>• Si vous ne suivez pas les règles/procédures et règles à propos des armes, vous serez Kické du serveur, puis suspendu de la Gendarmerie.</t>"],
	[40,"Règles du TeamSpeak",1,"<t size='0.8'>• Tous les gendarmes doivent être sur Teamspeak 3 dans le channel qui leur à été attribué. Si vous n'êtes pas sur TeamSpeak et que vous êtes en jeu en tant que Gendarme, cela peut mener à votre suspension de la Gendarmerie.<br/>• Merci de rejoindre le TeamSpeak AVANT MÊME de rejoindre le serveur.</t>"],
	[41,"Illégal",0,"<t size='0.8'>Cette catégorie contient les règles sur toutes les armes / items / véhicules illégaux, ainsi que les règles pour les rebelles/criminels.</t>"],
	[42,"Règles Criminels",1,"<t size='0.8'>Un criminel est un civil ayant opté pour l'illégalité et le crime. Il n'est pas la pour tuer, il est la pour se faire de l'argent facilement en les soutirant des civils, ou en faisant du trafic de drogue. Vous tenez un minimum à votre vie, vous êtes avant tout un civil.<br/>• Être criminel n'excuse pas le Freekill(Voir la section 'Freekill' dans 'Règles générales')<br/>• Le RP criminel ne s'arrête pas juste aux braquages de banque et à attaquer les Gendarmes, plein de possibilités s'offrent à vous. Les seules limites sont celles de votre imagination, les règles sont juste la pour vous encadrer.<br/>• Evitez de braquer H24 les civils, du moins les nouveaux. Essayez d'attaquer des gros poissons / des riches, pensez aux nouveaux qui viennent d'arriver sur le serveur.</t>"],
	[43,"Règles Criminels",1,"<t size='0.8'>• Être dans un gang (groupe de criminels) n'est pas illégal, sauf lorsque des crimes sont commis.<br/>• Être dans une planque de gang n'est pas illégal, sauf si vous prenez part à des activités illégales.<br/>• Les gangs peuvent attaquer et contrôler certaines zones. Les autres gangs peuvent s'affronter pour contrôler ces dites-zones.<br/>• Pour déclarer la guerre à un autre groupe, le leader devra annoncer cette décision sur le forum et en informer les hauts-gradés du gang adverse.<br/>• Les groupes ne doivent pas tuer les civils non armés, si ils font partis d'un groupe adverse, ou si ils sont dans votre campement.<br/>• Les gangs ne doivent pas tuer les civils, sauf s'ils représentent une menace. Tuer un civil qui ne coopére pas est considéré comme du Freekill, vous pouvez cependant le blesser, ou en faire ce que vous voulez. Imaginez une scène RP sympa si un civil ne coopére pas. Si il persiste, selon la situation, vous êtes en droit de l'abattre.</t>"],
	[44,"Véhicules illégaux",1,"<t size='0.8'>Un civil en possession d'un des véhicules suivants pourra être arrêté par les forces de Gendarmerie, en suivant la procédure à suivre.<br/><br/>• Ifrit (HMG/non HMG)<br/>• Tout véhicule de Gendarmerie (Hunter, Hellcat, Ghost-Haw, etc.)<br/>• CH-49 Mohawk<br/>• Tout-terrain armé<br/>• Tout véhicule camo rebelle (Orca, Hummingbird, etc.)</t>"],
	[45,"Armes illégales",1,"<t size='0.8'>Un civil en possession d'une de ces armes pourra être arrêté par les forces de Gendarmerie, en suivant la procédure à suivre.<br/><br/>• Toute arme utilisant du calibre 5.45x39mm<br/>• Toute arme utilisant du calibre 7.62x39mm<br/>• Toute arme automatique de 9mm (Tec-9, Micro Uzi, Glock 18, etc.)<br/>• Toute arme utilisant du calibre .45<br/>• Toute arme utilisant du calibre .32<br/>• Toute arme étant réservée à la Gendarmerie</t>"],
	[46,"Objets et marchandises illégales",1,"<t size='0.8'>La possession des marchandises suivnates est illégale:<br/><br/>• Cocaïne<br/>• Héroïne<br/>• Cannabis<br/>• Marijuana<br/>• Méthamphétamine<br/>• Uranium (Qualité Militaire)<br/>• Moonshine<br/>• Cigares</t>• Fossiles</t>"],
	[47,"   ",0,"   "]
];
/*
*****************************
***** Talents Variables *****
*****************************
*/
life_talentInfo =
[
	[1,"ENDURANCE",0,0,0,"<t color='#FF0000'>La marche à pied, c'est votre truc.</t><br/><br/>Plus vous courrez, plus vous êtes entraîné. Facile, non ?",1,"icons\endurance.paa",0,1],
	[2,"Joggeur",1,1,0,"<t color='#FF0000'>Sprint max. boosté de 7%.</t><br/><br/>Vous courrez souvent avec vos potes le matin, votre forme s'est amélioré.",0,"",1,0],
	[3,"Entraîné",1,2,2,"<t color='#FF0000'>Sprint max. boosté de 12%.</t><br/><br/>Vous avez pris goût à la course à pied, vous vous entraînez tous les jours.",0,"",1,0],
	[4,"Olympique",1,3,3,"<t color='#FF0000'>Sprint max. boosté de 16%.</t><br/><br/>A force d'entraînement, vous avez atteint une forme digne d'un coureur olympique.",0,"",1,0],
	[5,"Usain Bolt",1,4,4,"<t color='#FF0000'>Sprint max. boosté de 20% + Capacité de stockage du sac multiplié par x1.3.</t><br/><br/>Vos efforts ont payés : votre sang contient du RedGull.",0,"",1,0],
	[6,"CONDUITE",0,0,0,"<t color='#FF0000'>Need for Speed.</t><br/><br/>Les limitations de vitesse sont faites pour ne pas être respectées.",1,"icons\conduite.paa",0,2],
	[7,"Jeune Conducteur",2,1,0,"<t color='#FF0000'>Boost de 7% de nitro utilisable sur les véhicules terrestres.</t><br/><br/>Votre pote garagiste vous à installé un petit système plutôt sympa.",0,"",1,0],
	[8,"Pilote",2,2,7,"<t color='#FF0000'>Boost de 15% de nitro utilisable sur les véhicules terrestres</t><br/><br/>Un peu de tuning par ci par là, et voilà.",0,"",1,0],
	[9,"Fou du volant",2,3,8,"<t color='#FF0000'>Boost de 20% de nitro utilisable sur les véhicules terrestres.</t><br/><br/>Vous aimez votre voiture. Vous aimez aller vite. Pourquoi ne pas aller encore + vite ?",0,"",1,0],
	[10,"Paul Walker",2,4,9,"<t color='#FF0000'>Boost de 27% de nitro utilisable sur les véhicules terrestres.</t><br/><br/>Vous êtes le roi du tuning sur Altis. La gendarmerie vous déteste, les meufs vous adorent.",0,"",1,0],
	[11,"MEDECINE",0,0,0,"<t color='#FF0000'>Vous avez toujours aimé réparer des trucs. Évidemment sur les gens, c'est plus marrant.</t><br/><br/>Soigner des gens, c'est plus qu'une passion pour vous.",1,"icons\medecine.paa",0,3],
	[12,"Infirmier",3,1,0,"<t color='#FF0000'>Le kit de premier soins soigne à 80 HP</t><br/><br/>Les antibiotiques, c'est pas automatique.",0,"",1,0],
	[13,"Dr. House",3,2,12,"<t color='#FF0000'>Le kit de premier soins soigne à 90 HP</t><br/><br/>Vous connaissez le corps humain par coeur, vous pourriez faire une greffe tout en faisant la cuisine.",0,"",1,0],
	[14,"CHIMIE",0,0,0,"<t color='#FF0000'>La meth, c'est de l'argent. Mais avant tout de la drogue.</t><br/><br/>Faites comme Walter White. Faites de la meth.",1,"icons\chimiste.paa",0,4],
	[15,"Apprenti",4,1,0,"<t color='#FF0000'>Recette donnant une méthamphétamine à 60% pure.</t><br/><br/>Vous commencez à comprendre les rudiments de la chimie.",0,"",1,0],
	[16,"Novice",4,2,15,"<t color='#FF0000'>Recette donnant une méthamphétamine à 75% pure.</t><br/><br/>Vous avez modifié légèrement votre recette. Heureusement pour vous, ça fonctionne.",0,"",1,0],
	[17,"Cuisinier",4,3,16,"<t color='#FF0000'>Recette donnant une méthamphétamine à 85% pure.</t><br/><br/>Vous avez suivi vos cours de chimie à l'école. Ca a fini par payer.",0,"",1,0],
	[18,"Walter White",4,4,17,"<t color='#FF0000'>Recette donnant une méthamphétamine à 97% pure.</t><br/><br/>Le travail, ça paie. La meth aussi. Votre empire cristallin s'étend dans toute l'Europe.",0,"",1,0],
	[19,"HACKING",0,0,0,"<t color='#FF0000'>Les nouvelles technologies au service du citoyen.</t><br/><br/>Le réseau, c'est la force des hackers.",1,"icons\hacker.paa",0,5],
	[20,"Noob",5,1,0,"<t color='#FF0000'>Traquer temporairement un véhicule grâce à un module GPS.</t><br/><br/>Le bouquin « L'informatique pour les nuls » vous à servi, vous pouvez traquer les déplacements d'une personne.",0,"",1,0],
	[21,"Black Hat",5,2,20,"<t color='#FF0000'>Traquer temporairement un véhicule aérien grâce à un module GPS.</t><br/><br/>Après avoir bidouillé le machin avec le truc, vous avez réussi à faire un bidule qui fonctionne.",0,"",1,0],
	[22,"Anonymous",5,3,21,"<t color='#FF0000'>Traquer temporairement une personne grâce à un module GPS.</t><br/><br/>01000010 01110010 01100001 01110110 01101111 00101100 00100000 01110110 01101111 01110101 01110011 00100000 01100001 01110110 01100101 01111010 00100000 01100100",0,"",1,0],
	[23,"MECANIQUE",0,0,0,"<t color='#FF0000'>Le cambouis et les clés anglaises, c'est sympa.</t><br/><br/>A force de réparer des véhicules, vous ne pouvez que devenir meilleur.",1,"icons\mecano.paa",0,6],
	[24,"Débrouillard",6,1,0,"<t color='#FF0000'>Temps de réparation réduit de 10%.</t><br/><br/>Vous savez manier le crique, la clef anglaise et changer une roue. C'est un bon début.",0,"",1,0],
	[25,"Réparateur",6,2,24,"<t color='#FF0000'>Temps de réparation réduit de 15%.</t><br/><br/>Pimp My Ride est votre émission préférée. Vous savez faire quelques trucs de plus.",0,"",1,0],
	[26,"Expert",6,3,25,"<t color='#FF0000'>Temps de réparation réduit de 25%.</t><br/><br/>Vous êtes né pour réparer des véhicules. Vous maniez le tournevis comme personne.",0,"",1,0],
	[27,"CROCHETAGE",0,0,0,"<t color='#FF0000'>Pourquoi acheter une voiture alors qu'on peut en avoir une gratuite ?</t><br/><br/>Forcer les serrures et voler des voitures, c'est pas bien.",1,"icons\crochetage.paa",0,7],
	[28,"Blédard",7,1,0,"<t color='#FF0000'>Temps pour crocheter une voiture réduit de 10%.</t><br/><br/>Tonton du bled vous à appris deux-trois trucs, vous commencez à comprendre.",0,"",1,0],
	[29,"Car-Jacker",7,2,28,"<t color='#FF0000'>Temps pour crocheter une voiture réduit de 17%.</t><br/><br/>Avec de l'expérience, vous avez appris les bases du crochetage.",0,"",1,0],
	[30,"Serrurier",7,3,29,"<t color='#FF0000'>Temps pour crocheter une voiture réduit de 25% + Pas d'alarme si échec.</t><br/><br/>Forcer une serrure est devenu pour vous un jeu d'enfant. Voitures à volonté.",0,"",1,0],
	[31,"Magicien",7,4,30,"<t color='#FF0000'>Possibilité de crochetage lorsque vous êtes menotté.</t><br/><br/>Vous êtes le David Coperfield du crochetage. Vous pouvez vous enlever de menottes sans les mains.",0,"",1,0],
	[32,"EXPLOSIFS",0,0,0,"<t color='#FF0000'>Boom.</t><br/><br/>Alimenter les fabricants d'explosifs en matière première peut vous rapporter quelques tuyaux sur leur fabrication.",1,"icons\explosifs.paa",0,8],
	[33,"Jihad",8,1,0,"<t color='#FF0000'>Possibilité d'acheter un petit engin explosif improvisé.</t><br/><br/>Votre voyage en Syrie vous a servi, vous savez fabriquer des trucs qui explosent.",0,"",1,0],
	[34,"Démolisseur",8,2,33,"<t color='#FF0000'>Possibilité d'acheter une bombe de vitesse (se place sous une voiture, se déclenche quand le conducteur roule au dessus de 50 km/h, et explose lorsque le conducteur roule en dessous de 50 Km/h).</t><br/><br/>Vous savez faire des trucs cools et vicieux avec les explosifs. Votre imagination est sans limites.",0,"",1,0],
	[35,"BRAQUAGE",0,0,0,"<t color='#FF0000'>Le braquage de A à Z, façon Altis.</t><br/><br/>Vendez les lingots d'or que vous avez dérobé à la banque après un braquage pour progresser.",1,"icons\braqueur.paa",0,9],
	[36,"Braqueur de Bijouterie",9,1,0,"<t color='#FF0000'>Temps pour braquer la banque réduit de trente secondes.</t><br/><br/>Jouer à Payday, ça sert. Vous connaissez les failles de la Résèrve d'Etat.",0,"",1,0],
	[37,"Cambrioleur",9,2,36,"<t color='#FF0000'>Temps pour braquer la banque réduit d'une minute.</t><br/><br/>Braquer plus, pour gagner plus. C'est ça, le business.",0,"",1,0],
	[38,"Hardline",9,3,37,"<t color='#FF0000'>Temps pour braquer la banque réduit d'une minute et trente secondes.</t><br/><br/>Votre travail d'équipe et votre sens de l'organisation ont portés leur fruits : vous êtes devenu un cambrioleur international.",0,"",1,0],
	[39,"FURTIVITE",0,0,0,"<t color='#FF0000'>Le citoyen modèle. Ou presque.</t><br/><br/>Ne tuez personne, ne vous faites pas mettre de menottes, ne mourrez pas, ne vous faites pas verbaliser, et tout se passera bien. Plus le temps passe en remplissant ces conditions, plus vous progresser. Si une de ces choses vous arrive, le temps est remis à zéro.",1,"icons\furtif.paa",0,10],
	[40,"Citoyen modèle",10,1,0,"<t color='#FF0000'>Possibilité d'acheter des grenades lacrymogènes.</t><br/><br/>Se fondre dans le décor, s'adapter, c'est ça la survie.",0,"",1,0],
	[41,"Ombre",10,2,40,"<t color='#FF0000'>Possibilité d'acheter des doses d'adrénaline (visée + stable, aucune sensation de fatigue).</t><br/><br/>Personne ne vous remarque, personne ne fait attention à vous.",0,"",1,0],
	[42,"Ninja",10,3,41,"<t color='#FF0000'>Possibilité d'acheter un flash-ball (incapacitant).</t><br/><br/>Vous ne vous êtes jamais attiré d'ennuis, vous avez une discrétion à toute épreuve. Vous êtes désormais un ninja.",0,"",1,0],
	[43,"MINAGE",0,0,0,"<t color='#FF0000'>Adoptez-les !</t><br/><br/>Ne laissez pas les pioches passer l'hiver seul.",1,"icons\mineur.paa",0,11],
	[44,"Galibot",11,1,0,"<t color='#FF0000'>Réduction du temps de minage de 25%.</t><br/><br/>Vous avez trouvé votre pioche, maintenant faut apprendre a s'en servir.",0,"",1,0],
	[45,"Sainte Barbe",11,2,44,"<t color='#FF0000'>Réduction du temps de minage de 50%.</t><br/><br/>Oula ! La pioche vous à fait de sacrés biscoteaux.",0,"",1,0],
	[46,"   ",0,0,0,"   ",0,"",0,0]
];
/*
*****************************
****** Stat Variables *******
*****************************
*/
stat_chem = 0;
stat_hack = 0;
stat_hunt = 0;
stat_drive = 0;
stat_endu = 0;
stat_meca = 0;
stat_medic = 0;
stat_lockpick = 0;
stat_boom = 0;
stat_holdup = 0;
stat_surv = 0;
stat_coppoints = 0;
stat_civpoints = 0;
stat_mine = 0;
life_runned = 0;
life_drived = 0;
chem_state = 0;
hack_state = 0;
hunt_state = 0;
drive_state = 0;
endu_state = 0;
meca_state = 0;
medic_state = 0;
lockpick_state = 0;
boom_state = 0;
holdup_state = 0;
surv_state = 0;
civ_state = 0;
cop_state = 0;
mine_state = 0;
stat_rebpoints = 0;
reb_state = 0;
life_drink = 0;
life_adre_effect = time;
hack_quest = 0;
life_trackerInUse = false;