#include "..\..\script_macros.hpp"
/*
    File: fn_copLoadout.sqf
    Author: Bryan "Tonic" Boardwine
    Edited: Itsyuka
    
    Description:
    Loads the cops out with the default gear.
*/
private["_handle"];
_handle = [] spawn life_fnc_stripDownPlayer;
waitUntil {scriptDone _handle};

//Load player with default cop gear.
switch(FETCH_CONST(life_coplevel)) do
{
	case 1: {
		player addUniform "hightline_gendarmerie_gilet";
		player addVest "V_Police_light";
		player addHeadGear "hightline_gendarmerie_cap_01";
		player addBackpack "ALFR_Police_Bags";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
		player addGoggles "G_Aviator";
		player addWeapon "DDOPP_X26";
		player addMagazine "DDOPP_1Rnd_X26";
		player addMagazine "DDOPP_1Rnd_X26";
		player addMagazine "DDOPP_1Rnd_X26";
		player addMagazine "DDOPP_1Rnd_X26";
		player addMagazine "DDOPP_1Rnd_X26";
		player addMagazine "DDOPP_1Rnd_X26";
		player addMagazine "DDOPP_1Rnd_X26";
		player addMagazine "DDOPP_1Rnd_X26";
		player addMagazine "DDOPP_1Rnd_X26";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};
	case 2: {
		player addUniform "hightline_gendarmerie_gilet";
		player addVest "V_Police_medium";
		player addHeadGear "hightline_gendarmerie_cap_01";
		player addBackpack "ALFR_Police_Bags";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
		player addGoggles "G_Aviator";
		player addWeapon "DDOPP_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};	
	case 3: {
		player addUniform "hightline_gendarmerie_03";
		player addVest "V_Police_heavy";
		player addHeadGear "ALE_H_Calot";
		player addBackpack "ALFR_Police_Bags";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
		player addGoggles "G_Aviator";
		player addWeapon "DDOPP_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};
	case 4: {
		player addUniform "hightline_gendarmerie_03";
		player addVest "V_Police_heavy";
		player addHeadGear "ALE_H_Calot";
		player addBackpack "ALFR_Police_Bags";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
		player addGoggles "G_Aviator";
		player addWeapon "DDOPP_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};
	case 5: {
		player addUniform "hightline_gendarmerie_03";
		player addVest "V_Police_heavy";
		player addHeadGear "ALE_H_Calot";
		player addBackpack "ALFR_Police_Bags";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
		player addGoggles "G_Aviator";
		player addWeapon "DDOPP_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};
	case 6: {
		player addUniform "hightline_gendarmerie_02";
		player addVest "V_Police_heavy";
		player addHeadGear "ALE_H_Calot";
		player addBackpack "ALFR_Police_Bags";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
		player addGoggles "G_Aviator";
		player addWeapon "DDOPP_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};
	case 7: {
		player addUniform "hightline_gendarmerie_02";
		player addVest "V_Police_heavy";
		player addHeadGear "ALE_H_Calot";
		player addBackpack "ALFR_Police_Bags";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
		player addGoggles "G_Aviator";
		player addWeapon "DDOPP_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};
	case 8: {
		player addUniform "hightline_gendarmerie_02";
		player addVest "V_Police_heavy";
		player addHeadGear "ALE_H_Calot";
		player addBackpack "ALFR_Police_Bags";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
		player addGoggles "G_Aviator";
		player addWeapon "DDOPP_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};
    case 9: {
		player addUniform "hightline_gendarmerie_02";
		player addVest "V_Police_heavy";
		player addHeadGear "ALE_H_Calot";
		player addBackpack "ALFR_Police_Bags";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
        player addItemToBackpack "FirstAidKit";
		player addGoggles "G_Aviator";
		player addWeapon "DDOPP_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addMagazine "DDOPP_3Rnd_X3";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};
	default {
		player addUniform "U_Rangemaster";
		player addVest "V_TacVest_blk_POLICE";
		player addHeadGear "H_Cap_police";
		player addBackpack "B_Kitbag_cbr";
		player addGoggles "G_Shades_Black";
		player addWeapon "hgun_Rook40_F";
		player addMagazine "16Rnd_9x21_Mag";
		player addMagazine "16Rnd_9x21_Mag";
		player addMagazine "16Rnd_9x21_Mag";
		player addWeapon "arifle_sdar_F";
		player addMagazine "20Rnd_556x45_UW_mag";
		player addMagazine "20Rnd_556x45_UW_mag";
		player addMagazine "20Rnd_556x45_UW_mag";
		player addItem "ItemMap";
		player assignItem "ItemMap";
		player addItem "ItemCompass";
		player assignItem "ItemCompass";
		player addItem "ItemGPS";
		player assignItem "ItemGPS";
        player addWeapon "Rangefinder";
        player addItem "pmc_earpiece";
        player assignItem "pmc_earpiece";
	};
};







[] call life_fnc_playerSkins;
[] call life_fnc_saveGear;